spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.application.name=ecommerce
# H2 Database URL (In-memory database named 'testdb')
spring.datasource.url=jdbc:h2:file:./TriTeam-ECommerce-Platform/ecommerce/data
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable Hibernate/JPA to automatically create tables based on your @Entity classes (like User)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Tells Spring Boot to wait until database tables have been created before running data.sql
spring.jpa.defer-datasource-initialization=true

# Forces Spring Boot to initialize SQL when the application starts
spring.sql.init.mode=always