spring.application.name=ecommerce
# H2 Database URL (In-memory database named 'testdb')
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable Hibernate/JPA to automatically create tables based on your @Entity classes (like User)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true